version: "3.7"

services:
    nginx:
        container_name: nginx
        image: nginx:1.17-alpine
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./app/public:/usr/src/app
            - ./log/nginx/:/var/log/nginx
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm

    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
            args:
                USER_ID: ${HOST_USER_ID}
                GROUP_ID: ${HOST_GROUP_ID}
        restart: on-failure
        ports:
            - ${PHP_FPM_PORT}:9000
        volumes:
            - ./app/:/usr/src/app
            - ./log/php-fpm/xdebug.log:/var/log/xdebug.log
            - ./config/php-fpm/php-fpm.ini:/usr/local/etc/php/conf.d/php-fpm.ini
            - ./config/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        depends_on:
            - mysql

    mysql:
        container_name: mysql
        image: mysql:8.0
        restart: on-failure
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./docker/mysql/data:/var/lib/mysql

    adminer:
        container_name: adminer
        image: adminer
        restart: on-failure
        ports:
            - ${ADMINER_PORT}:8080
